### PR TITLE
add support for ContractInvocation

### PR DESCRIPTION
**Pull request by artmur**
add support for ContractInvocation

### CODE REVIEW

**Comment by Tolsi** [comment]
Nice job! But can you also add the (de)serializers tests for created objects like ContractInvocationTransaction, InvocationBinaryArg? You can check the other tests in test/java/com/wavesplatform/wavesj/json/ser and deser.

**Comment by artmur** [comment]
there is no need in such tests because one big ContractInvocationITest covers all cases

**Comment by Tolsi** [comment]
Yes, it does a round-trip, but for example, it does not check that json through api successfully parses the transaction.

**Comment by artmur** [comment]
Ser and Deser tests have been added

**Comment by Tolsi** [comment]
Thanks!

**Pull request merged**
